/*
 * HomePage.java
 *
 * Created on __DATE__, __TIME__
 */

package Main;

import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;

import Customer.CustomerMain;
import Hall.HallMain;
import Movie.MovieMain;
import Play.PlayMain;
import Sale.SaleMain;
import Statistics.BoxOffice;
import Statistics.DailySales;
import Statistics.ReportOutput;

/**
 *
 * @author  __USER__
 */
public class HomePage extends javax.swing.JPanel {
	JFrame jFrame = new JFrame();
	NavigationBar navigationBar = null;

	/** Creates new form HomePage */
	public HomePage(JFrame jf) {
		initComponents();
		jFrame = jf;
		navigationBar = new NavigationBar(jFrame);
		navigationBar.setLocation(30, 0);
		navigationBar.setSize(110, 430);
		navigationBar.setVisible(false);
		jFrame.add(navigationBar);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLayeredPane1 = new javax.swing.JLayeredPane();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();
		jLabel6 = new javax.swing.JLabel();
		jLabel7 = new javax.swing.JLabel();
		jLabel8 = new javax.swing.JLabel();
		jLabel9 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jLabel10 = new javax.swing.JLabel();

		jLabel1.setForeground(new java.awt.Color(255, 204, 204));
		jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/images/未标题-1_18.png"))); // NOI18N
		jLabel1.setText("\u5f71\u7247\u7ba1\u7406");
		jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jLabel1MouseClicked(evt);
			}
		});
		jLabel1.setBounds(70, 50, 190, 110);
		jLayeredPane1.add(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

		jLabel2.setForeground(new java.awt.Color(255, 255, 255));
		jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/images/未标题-1_14.png"))); // NOI18N
		jLabel2.setText("\u5f71\u5385\u7ba1\u7406");
		jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jLabel2MouseClicked(evt);
			}
		});
		jLabel2.setBounds(320, 50, 190, 116);
		jLayeredPane1.add(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

		jLabel3.setForeground(new java.awt.Color(255, 255, 255));
		jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/images/未标题-1_13.png"))); // NOI18N
		jLabel3.setText("\u573a\u6b21\u7ba1\u7406");
		jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jLabel3MouseClicked(evt);
			}
		});
		jLabel3.setBounds(560, 40, 190, 130);
		jLayeredPane1.add(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

		jLabel5.setForeground(new java.awt.Color(255, 204, 204));
		jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/images/未标题-1_04.png"))); // NOI18N
		jLabel5.setText("\u987e\u5ba2\u7ba1\u7406");
		jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jLabel5MouseClicked(evt);
			}
		});
		jLabel5.setBounds(70, 190, 190, 120);
		jLayeredPane1.add(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);

		jLabel6.setForeground(new java.awt.Color(255, 255, 255));
		jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/images/未标题-1_06.png"))); // NOI18N
		jLabel6.setText("\u552e\u7968");
		jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jLabel6MouseClicked(evt);
			}
		});
		jLabel6.setBounds(320, 190, 170, 130);
		jLayeredPane1.add(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);

		jLabel7.setForeground(new java.awt.Color(255, 204, 204));
		jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/images/未标题-1_19.png"))); // NOI18N
		jLabel7.setText("\u7968\u623f\u7edf\u8ba1");
		jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jLabel7MouseClicked(evt);
			}
		});
		jLabel7.setBounds(70, 330, 190, 117);
		jLayeredPane1.add(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);

		jLabel8.setForeground(new java.awt.Color(255, 204, 204));
		jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/images/未标题-1_11.png"))); // NOI18N
		jLabel8.setText("\u7968\u623f\u5206\u6790");
		jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jLabel8MouseClicked(evt);
			}
		});
		jLabel8.setBounds(320, 330, 190, 130);
		jLayeredPane1.add(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);

		jLabel9.setForeground(new java.awt.Color(255, 255, 255));
		jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/images/未标题-1_05.png"))); // NOI18N
		jLabel9.setText("\u62a5\u8868\u8f93\u51fa");
		jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jLabel9MouseClicked(evt);
			}
		});
		jLabel9.setBounds(560, 190, 190, 130);
		jLayeredPane1.add(jLabel9, javax.swing.JLayeredPane.DEFAULT_LAYER);

		jLabel4.setForeground(new java.awt.Color(255, 204, 204));
		jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/images/未标题-1_12.png"))); // NOI18N
		jLabel4.setText("\u9000\u51fa");
		jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jLabel4MouseClicked(evt);
			}
		});
		jLabel4.setBounds(560, 330, 180, 110);
		jLayeredPane1.add(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);

		jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/img/timg.jpg"))); // NOI18N
		jLabel10.setBounds(-170, -70, 1010, 620);
		jLayeredPane1.add(jLabel10, javax.swing.JLayeredPane.DEFAULT_LAYER);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 800,
				Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jLayeredPane1, javax.swing.GroupLayout.Alignment.TRAILING,
				javax.swing.GroupLayout.DEFAULT_SIZE, 494, Short.MAX_VALUE));
	}// </editor-fold>
	//GEN-END:initComponents

	private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {
		// TODO add your handling code here:
		jFrame.setVisible(false);
		Login login = new Login();
		login.setVisible(true);
		jFrame.dispose();
	}

	private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {
		// TODO add your handling code here:
		ReportOutput reportOutput = new ReportOutput();
		reportOutput.setVisible(true);
		reportOutput.setLocation(140, 0);
		reportOutput.setSize(600, 400);
		jFrame.add(reportOutput);
		jFrame.setTitle("报表输出");
		navigationBar.setVisible(true);
		this.setVisible(false);
	}

	private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {
		// TODO add your handling code here:
		BoxOffice boxOffice = new BoxOffice();
		boxOffice.setVisible(true);
		boxOffice.setLocation(140, 0);
		boxOffice.setSize(600, 400);
		jFrame.add(boxOffice);
		jFrame.setTitle("票房分析");
		navigationBar.setVisible(true);
		this.setVisible(false);
	}

	private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {
		// TODO add your handling code here:
		DailySales dailySales = new DailySales();
		dailySales.setVisible(true);
		dailySales.setLocation(140, 0);
		dailySales.setSize(600, 400);
		jFrame.add(dailySales);
		jFrame.setTitle("票房统计");
		navigationBar.setVisible(true);
		this.setVisible(false);
	}

	private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {
		// TODO add your handling code here:
		SaleMain saleMain = new SaleMain();
		saleMain.setVisible(true);
		saleMain.setLocation(140, 0);
		saleMain.setSize(600, 400);
		jFrame.add(saleMain);
		jFrame.setTitle("售票");
		navigationBar.setVisible(true);
		this.setVisible(false);
	}

	private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {
		// TODO add your handling code here:
		CustomerMain customerMain = new CustomerMain();
		customerMain.setVisible(true);
		customerMain.setLocation(140, 0);
		customerMain.setSize(600, 400);
		jFrame.add(customerMain);
		jFrame.setTitle("顾客管理");
		navigationBar.setVisible(true);
		this.setVisible(false);
	}

	private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {
		// TODO add your handling code here:
		PlayMain playMain = new PlayMain();
		playMain.setVisible(true);
		playMain.setLocation(140, 0);
		playMain.setSize(600, 700);
		jFrame.add(playMain);
		jFrame.setTitle("场次管理");
		navigationBar.setVisible(true);
		this.setVisible(false);
	}

	private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {
		// TODO add your handling code here:
		HallMain hallMain = new HallMain();
		hallMain.setVisible(true);
		hallMain.setLocation(140, 20);
		hallMain.setSize(600, 500);
		jFrame.add(hallMain);
		jFrame.setTitle("影厅管理");
		navigationBar.setVisible(true);
		this.setVisible(false);
	}

	private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {
		// TODO add your handling code here:
		MovieMain movieMain = new MovieMain();
		movieMain.setVisible(true);
		movieMain.setLocation(140, 0);
		movieMain.setSize(600, 494);
		jFrame.add(movieMain);
		jFrame.setTitle("影片管理");
		navigationBar.setVisible(true);
		this.setVisible(false);
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel10;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JLayeredPane jLayeredPane1;
	// End of variables declaration//GEN-END:variables

}