/*
 * Login.java
 *
 * Created on __DATE__, __TIME__
 */

package Main;

import java.sql.Connection;

import User.LoginID;
import User.User;
import UserDao.CustomerDao;
import UserDao.UserDao;
import Bool.Bool;
import connect.Db;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.UIManager;

/**
 *
 * @author  __USER__
 */
public class Login extends javax.swing.JFrame {
	private Db db = new Db();
	private Bool bool = new Bool();
	//private User user =new User();
	private UserDao userDao = new UserDao();

	/** Creates new form Login */
	public Login() {
		initComponents();
		this.setLocationRelativeTo(null);
		try {
			String path = "icon_film.png";
			Image img = ImageIO.read(this.getClass().getResource(path));
			this.setIconImage(img);
		} catch (Exception e) {
			// TODO: handle exception
			e.printStackTrace();
		}
		this.setLayout(null);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLayeredPane1 = new javax.swing.JLayeredPane();
		jTextField1 = new javax.swing.JTextField();
		jLabel1 = new javax.swing.JLabel();
		jCheckBox1 = new javax.swing.JCheckBox();
		jLabel2 = new javax.swing.JLabel();
		jButton1 = new javax.swing.JButton();
		jPasswordField1 = new javax.swing.JPasswordField();
		jLabel3 = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("\u7528\u6237\u767b\u5f55");

		jTextField1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextField1ActionPerformed(evt);
			}
		});
		jTextField1.setBounds(110, 70, 190, 23);
		jLayeredPane1.add(jTextField1, javax.swing.JLayeredPane.DEFAULT_LAYER);

		jLabel1.setForeground(new java.awt.Color(43, 67, 96));
		jLabel1.setText("\u7528\u6237\u540d/username");
		jLabel1.setBounds(110, 40, 120, 17);
		jLayeredPane1.add(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

		jCheckBox1.setFont(new java.awt.Font("微软雅黑", 0, 10));
		jCheckBox1.setForeground(new java.awt.Color(43, 67, 96));
		jCheckBox1.setText("\u8bb0\u4f4f\u7528\u6237\u540d\u548c\u5bc6\u7801");
		jCheckBox1.setBounds(110, 170, 140, 23);
		jLayeredPane1.add(jCheckBox1, javax.swing.JLayeredPane.DEFAULT_LAYER);

		jLabel2.setForeground(new java.awt.Color(43, 67, 96));
		jLabel2.setText("\u5bc6\u7801/password");
		jLabel2.setBounds(110, 100, 86, 17);
		jLayeredPane1.add(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

		jButton1.setBackground(new java.awt.Color(43, 67, 93));
		jButton1.setForeground(new java.awt.Color(255, 255, 255));
		jButton1.setText("\u7acb\u5373\u767b\u5f55");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});
		jButton1.setBounds(110, 210, 190, 25);
		jLayeredPane1.add(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);
		jPasswordField1.setBounds(110, 130, 190, 21);
		jLayeredPane1.add(jPasswordField1,
				javax.swing.JLayeredPane.DEFAULT_LAYER);
		jLabel3.setBounds(0, 0, 400, 300);
		jLayeredPane1.add(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400,
				Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300,
				Short.MAX_VALUE));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		String userName = this.jTextField1.getText();
		String passWord = new String(this.jPasswordField1.getPassword());
		if (Bool.isEmpty(userName)) {
			JOptionPane.showMessageDialog(null, "用户名不能为空!");
			return;
		}
		if (Bool.isEmpty(passWord)) {
			JOptionPane.showMessageDialog(null, "密码不能为空!");
			return;
		}
		User user = new User();
		user.setUserName(userName);
		user.setPassWord(passWord);
		Connection con = db.getCon();
		User currentUser = userDao.login(con, user);
		if (currentUser != null) {
			if(currentUser.getUserLevel()==1 ){
				JOptionPane.showMessageDialog(null, "登录成功！\nID："
						+ currentUser.getId() + "\n用户名："
						+ currentUser.getUserName() );
						//+ "\n登录密码："+ currentUser.getPassWord());
				this.jTextField1.setText("");
				this.jPasswordField1.setText("");
				new Main().setVisible(true);
				this.dispose();
			}else{
				JOptionPane.showMessageDialog(null, "登录成功！\nID："
						+ currentUser.getId() + "\n用户名："
						+ currentUser.getUserName() );
						//+ "\n登录密码："+ currentUser.getPassWord());
				this.jTextField1.setText("");
				this.jPasswordField1.setText("");
				CustomerDao dao = new CustomerDao();
				LoginID.getInstance().CusId = dao.getCus_id(currentUser.getId());
				new TicketMain().setVisible(true);
				this.dispose();
			}
		} else {
			JOptionPane.showMessageDialog(null, "不存在该用户名！");
			this.jTextField1.setText("");
			this.jPasswordField1.setText("");
		}
	}

	private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		try {
			JFrame.setDefaultLookAndFeelDecorated(true);
			UIManager.setLookAndFeel("com.jtattoo.plaf.mcwin.McWinLookAndFeel");
			} catch (Exception ex) {
				ex.printStackTrace();
			}
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Login().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JCheckBox jCheckBox1;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLayeredPane jLayeredPane1;
	private javax.swing.JPasswordField jPasswordField1;
	private javax.swing.JTextField jTextField1;
	// End of variables declaration//GEN-END:variables

}