/*
 * Main.java
 *
 * Created on __DATE__, __TIME__
 */

package Main;

import java.awt.Image;

import javax.imageio.ImageIO;

import Chat.BarChart;

/**
 *
 * @author  __USER__
 */
public class Main extends javax.swing.JFrame {

	/** Creates new form Main */
	public Main() {
		initComponents();
		this.setLocationRelativeTo(null);
		try {
			String path = "icon_film.png";
			Image img = ImageIO.read(this.getClass().getResource(path));
			this.setIconImage(img);
		} catch (Exception e) {
			// TODO: handle exception
			e.printStackTrace();
		}
		this.setLayout(null);
		HomePage homePage = new HomePage(this);
		homePage.setVisible(true);
		homePage.setLocation(0, 0);
		homePage.setSize(800, 494);
		this.add(homePage);
		this.setTitle("Ê×Ò³");

	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 800,
				Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 494,
				Short.MAX_VALUE));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Main().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	// End of variables declaration//GEN-END:variables

}