/*
 * NavigationBar.java
 *
 * Created on __DATE__, __TIME__
 */

package Main;

import javax.swing.JFrame;

import com.sun.org.apache.bcel.internal.generic.NEW;

import Customer.CustomerMain;
import Hall.HallMain;
import Movie.MovieMain;
import Play.PlayMain;
import Sale.SaleMain;
import Statistics.BoxOffice;
import Statistics.DailySales;
import Statistics.ReportOutput;

/**
 *
 * @author  __USER__
 */
public class NavigationBar extends javax.swing.JPanel {
	/** Creates new form NavigationBar */
	JFrame jFrame = null;
	NavigationBar navigationBar = null;

	public NavigationBar(JFrame jf) {
		initComponents();
		jFrame = jf;

	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLayeredPane1 = new javax.swing.JLayeredPane();
		jButton1 = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();
		jButton3 = new javax.swing.JButton();
		jButton4 = new javax.swing.JButton();
		jButton5 = new javax.swing.JButton();
		jButton6 = new javax.swing.JButton();
		jButton7 = new javax.swing.JButton();
		jButton8 = new javax.swing.JButton();
		jButton9 = new javax.swing.JButton();

		jButton1.setText("\u56de\u5230\u9996\u9875");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});
		jButton1.setBounds(0, 20, 90, 25);
		jLayeredPane1.add(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);

		jButton2.setText("\u5f71\u7247\u7ba1\u7406");
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});
		jButton2.setBounds(0, 60, 90, 25);
		jLayeredPane1.add(jButton2, javax.swing.JLayeredPane.DEFAULT_LAYER);

		jButton3.setText("\u5f71\u5385\u7ba1\u7406");
		jButton3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton3ActionPerformed(evt);
			}
		});
		jButton3.setBounds(0, 100, 90, 25);
		jLayeredPane1.add(jButton3, javax.swing.JLayeredPane.DEFAULT_LAYER);

		jButton4.setText("\u573a\u6b21\u7ba1\u7406");
		jButton4.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton4ActionPerformed(evt);
			}
		});
		jButton4.setBounds(0, 140, 90, 25);
		jLayeredPane1.add(jButton4, javax.swing.JLayeredPane.DEFAULT_LAYER);

		jButton5.setText("\u987e\u5ba2\u7ba1\u7406");
		jButton5.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton5ActionPerformed(evt);
			}
		});
		jButton5.setBounds(0, 180, 90, 25);
		jLayeredPane1.add(jButton5, javax.swing.JLayeredPane.DEFAULT_LAYER);

		jButton6.setText("\u552e\u7968");
		jButton6.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton6ActionPerformed(evt);
			}
		});
		jButton6.setBounds(0, 220, 90, 25);
		jLayeredPane1.add(jButton6, javax.swing.JLayeredPane.DEFAULT_LAYER);

		jButton7.setText("\u7968\u623f\u7edf\u8ba1");
		jButton7.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton7ActionPerformed(evt);
			}
		});
		jButton7.setBounds(0, 310, 90, 25);
		jLayeredPane1.add(jButton7, javax.swing.JLayeredPane.DEFAULT_LAYER);

		jButton8.setText("\u7968\u623f\u5206\u6790");
		jButton8.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton8ActionPerformed(evt);
			}
		});
		jButton8.setBounds(0, 350, 90, 25);
		jLayeredPane1.add(jButton8, javax.swing.JLayeredPane.DEFAULT_LAYER);

		jButton9.setText("\u62a5\u8868\u8f93\u51fa");
		jButton9.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton9ActionPerformed(evt);
			}
		});
		jButton9.setBounds(0, 390, 90, 25);
		jLayeredPane1.add(jButton9, javax.swing.JLayeredPane.DEFAULT_LAYER);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 105,
				javax.swing.GroupLayout.PREFERRED_SIZE));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jLayeredPane1, javax.swing.GroupLayout.Alignment.TRAILING,
				javax.swing.GroupLayout.DEFAULT_SIZE, 429, Short.MAX_VALUE));
	}// </editor-fold>
	//GEN-END:initComponents

	private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		jFrame.getContentPane().removeAll();

		navigationBar = new NavigationBar(jFrame);
		navigationBar.setLocation(30, 0);
		navigationBar.setSize(110, 430);
		navigationBar.setVisible(true);

		ReportOutput reportOutput = new ReportOutput();
		reportOutput.setVisible(true);
		reportOutput.setLocation(140, 0);
		reportOutput.setSize(600, 400);
		jFrame.add(reportOutput);
		jFrame.setTitle("报表输出");

		jFrame.add(navigationBar);
		jFrame.validate();
		jFrame.repaint();
	}

	private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {
		jFrame.getContentPane().removeAll();

		navigationBar = new NavigationBar(jFrame);
		navigationBar.setLocation(30, 0);
		navigationBar.setSize(110, 430);
		navigationBar.setVisible(true);
		
		BoxOffice boxOffice = new BoxOffice();
		boxOffice.setVisible(true);
		boxOffice.setLocation(140, 0);
		boxOffice.setSize(600, 400);
		jFrame.add(boxOffice);
		jFrame.setTitle("票房分析");

		jFrame.add(navigationBar);
		jFrame.validate();
		jFrame.repaint();
	}

	private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		jFrame.getContentPane().removeAll();

		navigationBar = new NavigationBar(jFrame);
		navigationBar.setLocation(30, 0);
		navigationBar.setSize(110, 430);
		navigationBar.setVisible(true);

		DailySales dailySales = new DailySales();
		dailySales.setVisible(true);
		dailySales.setLocation(140, 0);
		dailySales.setSize(600, 400);
		jFrame.add(dailySales);
		jFrame.setTitle("票房统计");

		jFrame.add(navigationBar);
		jFrame.validate();
		jFrame.repaint();
	}

	private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		jFrame.getContentPane().removeAll();

		navigationBar = new NavigationBar(jFrame);
		navigationBar.setLocation(30, 0);
		navigationBar.setSize(110, 430);
		navigationBar.setVisible(true);

		SaleMain saleMain = new SaleMain();
		saleMain.setVisible(true);
		saleMain.setLocation(140, 0);
		saleMain.setSize(600, 400);
		jFrame.add(saleMain);
		jFrame.setTitle("售票");

		jFrame.add(navigationBar);
		jFrame.validate();
		jFrame.repaint();
	}

	private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		jFrame.getContentPane().removeAll();

		navigationBar = new NavigationBar(jFrame);
		navigationBar.setLocation(30, 0);
		navigationBar.setSize(110, 430);
		navigationBar.setVisible(true);

		CustomerMain customerMain = new CustomerMain();
		customerMain.setVisible(true);
		customerMain.setLocation(140, 0);
		customerMain.setSize(600, 400);
		jFrame.add(customerMain);
		jFrame.setTitle("顾客管理");

		jFrame.add(navigationBar);
		jFrame.validate();
		jFrame.repaint();
	}

	private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		jFrame.getContentPane().removeAll();

		navigationBar = new NavigationBar(jFrame);
		navigationBar.setLocation(30, 0);
		navigationBar.setSize(110, 430);
		navigationBar.setVisible(true);

		PlayMain playMain = new PlayMain();
		playMain.setVisible(true);
		playMain.setLocation(140, 0);
		playMain.setSize(600, 700);

		jFrame.add(playMain);
		jFrame.setTitle("场次管理");
		jFrame.add(navigationBar);
		jFrame.validate();
		jFrame.repaint();
	}

	private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		jFrame.getContentPane().removeAll();

		navigationBar = new NavigationBar(jFrame);
		navigationBar.setLocation(30, 0);
		navigationBar.setSize(110, 430);
		navigationBar.setVisible(true);

		HallMain hallMain = new HallMain();
		hallMain.setVisible(true);
		hallMain.setLocation(140, 20);
		hallMain.setSize(600, 500);

		jFrame.add(hallMain);
		jFrame.setTitle("影厅管理");

		jFrame.add(navigationBar);
		jFrame.validate();
		jFrame.repaint();
	}

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		jFrame.getContentPane().removeAll();

		MovieMain movieMain = new MovieMain();
		movieMain.setVisible(true);
		movieMain.setLocation(140, 0);
		movieMain.setSize(600, 494);

		navigationBar = new NavigationBar(jFrame);
		navigationBar.setLocation(30, 0);
		navigationBar.setSize(110, 430);
		navigationBar.setVisible(true);

		jFrame.add(movieMain);
		jFrame.setTitle("影片管理");
		jFrame.add(navigationBar);
		jFrame.validate();
		jFrame.repaint();
	}

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		jFrame.getContentPane().removeAll();
		HomePage homePage = new HomePage(jFrame);
		homePage.setVisible(true);
		homePage.setLocation(0, 0);
		homePage.setSize(800, 494);
		jFrame.setTitle("首页");
		jFrame.add(homePage);
		jFrame.validate();
		jFrame.repaint();
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JButton jButton3;
	private javax.swing.JButton jButton4;
	private javax.swing.JButton jButton5;
	private javax.swing.JButton jButton6;
	private javax.swing.JButton jButton7;
	private javax.swing.JButton jButton8;
	private javax.swing.JButton jButton9;
	private javax.swing.JLayeredPane jLayeredPane1;
	// End of variables declaration//GEN-END:variables

}