/*
 * BoxOffice.java
 *
 * Created on __DATE__, __TIME__
 */

package Statistics;

import java.awt.GridLayout;

import Chat.BarChart;
import Chat.PieChart;

/**
 *
 * @author  __USER__
 */
public class BoxOffice extends javax.swing.JPanel {

	/** Creates new form BoxOffice */
	public BoxOffice() {
		initComponents();
		this.setLayout(new GridLayout(2, 2, 10, 10));
		this.add(new PieChart().getChartPanel());
		this.setBounds(0, 0, 600, 450);
		this.setVisible(true);

	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLayeredPane1 = new javax.swing.JLayeredPane();

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 600,
				Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 386,
				Short.MAX_VALUE));
	}// </editor-fold>
	//GEN-END:initComponents

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JLayeredPane jLayeredPane1;
	// End of variables declaration//GEN-END:variables

}