/*
 * ReportOutput.java
 *
 * Created on __DATE__, __TIME__
 */

package Statistics;

/**
 *
 * @author  __USER__
 */
public class ReportOutput extends javax.swing.JPanel {

	/** Creates new form ReportOutput */
	public ReportOutput() {
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLayeredPane1 = new javax.swing.JLayeredPane();
		jCheckBox4 = new javax.swing.JCheckBox();
		jButton1 = new javax.swing.JButton();
		jCheckBox1 = new javax.swing.JCheckBox();
		jCheckBox2 = new javax.swing.JCheckBox();
		jCheckBox3 = new javax.swing.JCheckBox();
		jComboBox1 = new javax.swing.JComboBox();
		jComboBox2 = new javax.swing.JComboBox();

		jCheckBox4.setText("\u9500\u552e\u989d\u6298\u7ebf\u56fe");
		jCheckBox4.setBounds(10, 130, 160, 25);
		jLayeredPane1.add(jCheckBox4, javax.swing.JLayeredPane.DEFAULT_LAYER);

		jButton1.setText("\u6253\u5370");
		jButton1.setBounds(150, 190, 130, 25);
		jLayeredPane1.add(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);

		jCheckBox1.setText("\u5404\u7535\u5f71\u7968\u623f\u67f1\u5f62\u56fe");
		jCheckBox1.setBounds(10, 70, 160, 25);
		jLayeredPane1.add(jCheckBox1, javax.swing.JLayeredPane.DEFAULT_LAYER);

		jCheckBox2
				.setText("\u5404\u7535\u5f71\u653e\u6620\u573a\u6b21\u548c\u4e0a\u5ea7\u7387\u67f1\u5f62\u56fe");
		jCheckBox2.setBounds(10, 100, 220, 25);
		jLayeredPane1.add(jCheckBox2, javax.swing.JLayeredPane.DEFAULT_LAYER);

		jCheckBox3.setText("\u5f71\u5385\u5b89\u6392\u8868");
		jCheckBox3
				.setActionCommand("\u672c\u65e5\u7684\u5f71\u5385\u573a\u6b21\u5b89\u6392\u8868");
		jCheckBox3.setBounds(10, 160, 140, 25);
		jLayeredPane1.add(jCheckBox3, javax.swing.JLayeredPane.DEFAULT_LAYER);

		jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] {
				"请选择月份", "一月", "二月", "三月", "四月", "五月", "六月", "七月", "八月", "九月",
				"十月", "十一月", "十二月" }));
		jComboBox1.setBounds(10, 30, 120, 23);
		jLayeredPane1.add(jComboBox1, javax.swing.JLayeredPane.DEFAULT_LAYER);

		jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] {
				"请选择日期", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10",
				"11", "12", "14", "14", "15", "16", "17", "18", "19", "20",
				"21", "22", "23", "24", "25", "26", "27", "28", "29", "30",
				"31" }));
		jComboBox2.setBounds(150, 30, 130, 23);
		jLayeredPane1.add(jComboBox2, javax.swing.JLayeredPane.DEFAULT_LAYER);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				layout.createSequentialGroup().addComponent(jLayeredPane1,
						javax.swing.GroupLayout.PREFERRED_SIZE, 329,
						javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
								Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				layout.createSequentialGroup().addComponent(jLayeredPane1,
						javax.swing.GroupLayout.PREFERRED_SIZE, 266,
						javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
								Short.MAX_VALUE)));
	}// </editor-fold>
	//GEN-END:initComponents

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JCheckBox jCheckBox1;
	private javax.swing.JCheckBox jCheckBox2;
	private javax.swing.JCheckBox jCheckBox3;
	private javax.swing.JCheckBox jCheckBox4;
	private javax.swing.JComboBox jComboBox1;
	private javax.swing.JComboBox jComboBox2;
	private javax.swing.JLayeredPane jLayeredPane1;
	// End of variables declaration//GEN-END:variables

}