/*
 * HallMain.java
 *
 * Created on __DATE__, __TIME__
 */

package Hall;

import java.util.List;
import java.util.Vector;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import Bool.Bool;
import User.Customer;
import User.Hall;
import UserDao.HallDao;

/**
 *
 * @author  __USER__
 */
public class HallMain extends javax.swing.JPanel {
	HallDao hallDao = new HallDao();

	/** Creates new form HallMain */
	public HallMain() {
		initComponents();
		fillTable(new Hall());
		resetValue();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLayeredPane1 = new javax.swing.JLayeredPane();
		jScrollPane1 = new javax.swing.JScrollPane();
		jTable1 = new javax.swing.JTable();
		jComboBox1 = new javax.swing.JComboBox();
		jComboBox4 = new javax.swing.JComboBox();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jLabel6 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabel8 = new javax.swing.JLabel();
		jTextField2 = new javax.swing.JTextField();
		jComboBox2 = new javax.swing.JComboBox();
		jComboBox3 = new javax.swing.JComboBox();
		jTextField3 = new javax.swing.JTextField();
		jTextField4 = new javax.swing.JTextField();
		jButton5 = new javax.swing.JButton();
		jButton6 = new javax.swing.JButton();
		jLabel5 = new javax.swing.JLabel();

		jTable1
				.setModel(new javax.swing.table.DefaultTableModel(
						new Object[][] {
								{ null, null, null, null, null, null, null },
								{ null, null, null, null, null, null, null },
								{ null, null, null, null, null, null, null },
								{ null, null, null, null, null, null, null },
								{ null, null, null, null, null, null, null } },
						new String[] { "影厅编号", "影厅名称", "行", "列", "座位数", "影厅规格",
								"影厅状态" }));
		jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mousePressed(java.awt.event.MouseEvent evt) {
				jTable1MousePressed(evt);
			}
		});
		jScrollPane1.setViewportView(jTable1);

		jScrollPane1.setBounds(40, 70, 550, 190);
		jLayeredPane1.add(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

		jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] {
				"影厅状态", "可用", "不可用" }));
		jComboBox1.addItemListener(new java.awt.event.ItemListener() {
			public void itemStateChanged(java.awt.event.ItemEvent evt) {
				jComboBox1ItemStateChanged(evt);
			}
		});
		jComboBox1.setBounds(180, 30, 74, 21);
		jLayeredPane1.add(jComboBox1, javax.swing.JLayeredPane.DEFAULT_LAYER);

		jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] {
				"影厅规格", "IMAX", "小", "大" }));
		jComboBox4.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jComboBox4MouseClicked(evt);
			}

			public void mousePressed(java.awt.event.MouseEvent evt) {
				jComboBox4MousePressed(evt);
			}
		});
		jComboBox4.addItemListener(new java.awt.event.ItemListener() {
			public void itemStateChanged(java.awt.event.ItemEvent evt) {
				jComboBox4ItemStateChanged(evt);
			}
		});
		jComboBox4.setBounds(40, 30, 100, 21);
		jLayeredPane1.add(jComboBox4, javax.swing.JLayeredPane.DEFAULT_LAYER);
		jLabel1.setBounds(0, 20, 600, 250);
		jLayeredPane1.add(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

		jLabel2.setText("\u5f71\u5385\u7f16\u53f7\uff1a");
		jLabel2.setBounds(40, 300, 60, 15);
		jLayeredPane1.add(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

		jLabel4.setText("\u5ea7\u4f4d\u6570\uff1a");
		jLabel4.setBounds(440, 300, 48, 15);
		jLayeredPane1.add(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);

		jLabel6.setText("\u5f71\u5385\u89c4\u683c\uff1a");
		jLabel6.setBounds(40, 340, 60, 15);
		jLayeredPane1.add(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);

		jLabel3.setText("\u5f71\u5385\u540d\u79f0\uff1a");
		jLabel3.setBounds(240, 300, 60, 15);
		jLayeredPane1.add(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

		jLabel8.setText("\u5f71\u5385\u72b6\u6001\uff1a");
		jLabel8.setBounds(240, 340, 60, 15);
		jLayeredPane1.add(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);

		jTextField2.setText("jTextField1");
		jTextField2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextField2ActionPerformed(evt);
			}
		});
		jTextField2.setBounds(110, 300, 90, 21);
		jLayeredPane1.add(jTextField2, javax.swing.JLayeredPane.DEFAULT_LAYER);

		jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] {
				"状态", "可用", "不可用" }));
		jComboBox2.setBounds(310, 340, 90, 21);
		jLayeredPane1.add(jComboBox2, javax.swing.JLayeredPane.DEFAULT_LAYER);

		jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] {
				"规格", "大", "小", "IMAX" }));
		jComboBox3.setBounds(110, 340, 90, 21);
		jLayeredPane1.add(jComboBox3, javax.swing.JLayeredPane.DEFAULT_LAYER);

		jTextField3.setText("jTextField2");
		jTextField3.setBounds(310, 300, 100, 21);
		jLayeredPane1.add(jTextField3, javax.swing.JLayeredPane.DEFAULT_LAYER);

		jTextField4.setText("jTextField3");
		jTextField4.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextField4ActionPerformed(evt);
			}
		});
		jTextField4.setBounds(500, 300, 100, 21);
		jLayeredPane1.add(jTextField4, javax.swing.JLayeredPane.DEFAULT_LAYER);

		jButton5.setText("\u91cd\u7f6e");
		jButton5.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton5ActionPerformed(evt);
			}
		});
		jButton5.setBounds(140, 380, 80, 23);
		jLayeredPane1.add(jButton5, javax.swing.JLayeredPane.DEFAULT_LAYER);

		jButton6.setLabel("\u4fee\u6539");
		jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jButton6MouseClicked(evt);
			}
		});
		jButton6.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton6ActionPerformed(evt);
			}
		});
		jButton6.setBounds(380, 380, 81, 23);
		jLayeredPane1.add(jButton6, javax.swing.JLayeredPane.DEFAULT_LAYER);
		jLabel5.setBounds(40, 280, 600, 150);
		jLayeredPane1.add(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 684,
				Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 468,
				Short.MAX_VALUE));
	}// </editor-fold>
	//GEN-END:initComponents

	private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {
		// TODO add your handling code here:
		Hall hall = new Hall();
		String halstateselect = this.jComboBox1.getSelectedItem().toString();
		if (halstateselect == "影厅状态") {
			halstateselect = "";
		}
		hall.setHal_state(halstateselect);
		fillTable(hall);
	}

	private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jComboBox4ItemStateChanged(java.awt.event.ItemEvent evt) {
		// TODO add your handling code here:
		Hall hall = new Hall();
		String halkindselect = this.jComboBox4.getSelectedItem().toString();
		if (halkindselect == "影厅规格") {
			halkindselect = "";
		}
		hall.setHal_kind(halkindselect);
		fillTable(hall);
	}

	private void jComboBox4MousePressed(java.awt.event.MouseEvent evt) {
		// TODO add your handling code here:

	}

	private void jComboBox4MouseClicked(java.awt.event.MouseEvent evt) {
		// TODO add your handling code here:

	}

	private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		resetValue();
	}

	private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {
		// TODO add your handling code here:

		int row = jTable1.getSelectedRow();//取得表格选中行
		if (row > -1) {
			String hal_id = jTable1.getValueAt(row, 0).toString();
			String hal_name = this.jTextField3.getText();
			int hal_count = Integer.parseInt(this.jTextField4.getText());
			String hal_kind = this.jComboBox3.getSelectedItem().toString();
			String hal_state = this.jComboBox2.getSelectedItem().toString();
			if (Bool.isEmpty(this.jTextField2.getText())) {
				JOptionPane.showMessageDialog(null, "请选择你要修改的记录！");
				return;
			}
			if (Bool.isEmpty(this.jTextField3.getText())) {
				JOptionPane.showMessageDialog(null, "影厅名称不能为空！");
				return;
			}
			if (Bool.isEmpty(this.jTextField4.getText())) {
				JOptionPane.showMessageDialog(null, "影厅座位数不能为空！");
				return;
			}
			if (hal_kind.equals("规格")) {
				JOptionPane.showMessageDialog(null, "请选择影厅规格！");
				return;
			}
			if (hal_state.equals("状态")) {
				JOptionPane.showMessageDialog(null, "请选择影厅状态！");
				return;
			}
			Hall hall = new Hall(hal_id, hal_name, hal_count, hal_kind,
					hal_state);
			int modifyNum = hallDao.update(hall);
			if (modifyNum == 1) {
				JOptionPane.showMessageDialog(null, "修改成功！");
				resetValue();
				this.fillTable(new Hall());
			} else {
				JOptionPane.showMessageDialog(null, "修改失败！");
			}

		} else {
			JOptionPane.showMessageDialog(null, "请选择要修改的数据！");
		}

	}

	private void fillTable(Hall hall) {
		// TODO Auto-generated method stub
		DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
		dtm.setRowCount(0);
		List<Hall> listHall = hallDao.list(hall.getHal_kind(), hall
				.getHal_state());
		if (listHall.size() != 0) {
			for (int i = 0; i < listHall.size(); i++) {
				hall = listHall.get(i);
				Vector v = new Vector();
				v.add(hall.getHal_id());
				v.add(hall.getHal_name());
				v.add(hall.getHal_rows());
				v.add(hall.getHal_seats());
				v.add(hall.getHal_count());
				v.add(hall.getHal_kind());
				v.add(hall.getHal_state());
				dtm.addRow(v);
			}
		}
	}

	private void resetValue() {
		// TODO Auto-generated method stub
		this.jTextField2.setText("");
		this.jTextField3.setText("");
		this.jTextField4.setText("");
		this.jComboBox2.setSelectedItem("状态");
		this.jComboBox3.setSelectedItem("规格");
	}

	private void jTable1MousePressed(java.awt.event.MouseEvent evt) {
		// TODO add your handling code here:
		int row = this.jTable1.getSelectedRow();
		this.jTextField2.setText(this.jTable1.getValueAt(row, 0).toString());
		this.jTextField3.setText(this.jTable1.getValueAt(row, 1).toString());
		this.jTextField4.setText(this.jTable1.getValueAt(row, 4).toString());
		//this.jComboBox2
		this.jComboBox3.setSelectedItem(this.jTable1.getValueAt(row, 5)
				.toString());
		this.jComboBox2.setSelectedItem(this.jTable1.getValueAt(row, 6)
				.toString());
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton5;
	private javax.swing.JButton jButton6;
	private javax.swing.JComboBox jComboBox1;
	private javax.swing.JComboBox jComboBox2;
	private javax.swing.JComboBox jComboBox3;
	private javax.swing.JComboBox jComboBox4;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JLayeredPane jLayeredPane1;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTable jTable1;
	private javax.swing.JTextField jTextField2;
	private javax.swing.JTextField jTextField3;
	private javax.swing.JTextField jTextField4;
	// End of variables declaration//GEN-END:variables

}