/*
 * PlayMain.java
 *
 * Created on __DATE__, __TIME__
 */

package Play;

import java.util.List;
import java.util.Vector;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import Bool.Bool;
import User.Customer;
import User.Hall;
import User.Movie;
import User.Play;
import UserDao.HallDao;
import UserDao.MovieDao;
import UserDao.PlayDao;

/**
 *
 * @author  __USER__
 */
public class PlayMain extends javax.swing.JPanel {
	PlayDao playDao = new PlayDao();
	HallDao hallDao = new HallDao();
	MovieDao movieDao = new MovieDao();
	List<Movie> movies = null;
	List<Hall> halls = null;

	/** Creates new form PlayMain */
	public PlayMain() {
		initComponents();
		fillTable(new Play());
		resetValue();
		halls = hallDao.list(null, null);
		for (int i = 0; i < halls.size(); i++) {
			Hall hall = halls.get(i);
			jComboBox3.addItem(hall.getHal_name());
			jComboBox2.addItem(hall.getHal_name());
		}
		movies = movieDao.list(null);
		for (int i = 0; i < movies.size(); i++) {
			Movie movie = movies.get(i);
			jComboBox1.addItem(movie.getName());
		}
	}



	private void fillTable(Play play) {
		// TODO Auto-generated method stub
		DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
		dtm.setRowCount(0);
		List<Play> listPlays = playDao.list(play.getMov_name(), play
				.getHal_name());
		if (listPlays.size() != 0) {
			for (int i = 0; i < listPlays.size(); i++) {
				play = listPlays.get(i);
				Vector v = new Vector();
				v.add(play.getPla_id());
				v.add(play.getHal_name());
				v.add(play.getHal_kind());
				v.add(play.getMov_name());
				v.add(play.getPla_starttime());
				v.add(play.getMov_time());
				v.add(play.getTic_price());
				v.add(play.getHal_id());
				v.add(play.getMov_id());
				dtm.addRow(v);
			}
		}
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLayeredPane1 = new javax.swing.JLayeredPane();
		jTextField1 = new javax.swing.JTextField();
		jButton4 = new javax.swing.JButton();
		jButton3 = new javax.swing.JButton();
		jScrollPane1 = new javax.swing.JScrollPane();
		jTable1 = new javax.swing.JTable();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jLabel6 = new javax.swing.JLabel();
		jTextField5 = new javax.swing.JTextField();
		jComboBox3 = new javax.swing.JComboBox();
		jButton5 = new javax.swing.JButton();
		jButton6 = new javax.swing.JButton();
		jComboBox1 = new javax.swing.JComboBox();
		jButton8 = new javax.swing.JButton();
		jTextField2 = new javax.swing.JTextField();
		jComboBox2 = new javax.swing.JComboBox();
		jTextField4 = new javax.swing.JTextField();
		jLabel5 = new javax.swing.JLabel();

		jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
			public void keyTyped(java.awt.event.KeyEvent evt) {
				jTextField1KeyTyped(evt);
			}
		});
		jTextField1.setBounds(30, 40, 110, 23);
		jLayeredPane1.add(jTextField1, javax.swing.JLayeredPane.DEFAULT_LAYER);

		jButton4.setText("\u67e5\u8be2");
		jButton4.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton4ActionPerformed(evt);
			}
		});
		jButton4.setBounds(170, 40, 70, 25);
		jLayeredPane1.add(jButton4, javax.swing.JLayeredPane.DEFAULT_LAYER);

		jButton3.setText("\u5220\u9664");
		jButton3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton3ActionPerformed(evt);
			}
		});
		jButton3.setBounds(440, 40, 70, 25);
		jLayeredPane1.add(jButton3, javax.swing.JLayeredPane.DEFAULT_LAYER);

		jScrollPane1.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mousePressed(java.awt.event.MouseEvent evt) {
				jScrollPane1MousePressed(evt);
			}
		});

		jTable1.setModel(new javax.swing.table.DefaultTableModel(
				new Object[][] { { null, null, null, null, null, null, null },
						{ null, null, null, null, null, null, null },
						{ null, null, null, null, null, null, null },
						{ null, null, null, null, null, null, null } },
				new String[] { "场次编号", "影厅名称", "影厅规格", "电影名称", "起始放映时间",
						"电影时长", "电影票价" }));
		jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mousePressed(java.awt.event.MouseEvent evt) {
				jTable1MousePressed(evt);
			}
		});
		jScrollPane1.setViewportView(jTable1);

		jScrollPane1.setBounds(30, 70, 560, 200);
		jLayeredPane1.add(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

		jLabel1.setText("\u7f16    \u53f7\uff1a");
		jLabel1.setBounds(50, 290, 52, 17);
		jLayeredPane1.add(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

		jLabel2.setText("\u5f71\u5385\u540d\u79f0\uff1a");
		jLabel2.setBounds(260, 290, 70, 17);
		jLayeredPane1.add(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

		jLabel3.setText("\u7535\u5f71\u540d\u79f0\uff1a");
		jLabel3.setBounds(50, 340, 60, 17);
		jLayeredPane1.add(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

		jLabel4.setText("\u653e\u6620\u65f6\u95f4\uff1a");
		jLabel4.setBounds(260, 340, 60, 17);
		jLayeredPane1.add(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);

		jLabel6.setText("\u7535\u5f71\u7968\u4ef7\uff1a");
		jLabel6.setBounds(450, 310, 70, 17);
		jLayeredPane1.add(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);

		jTextField5.setText("jTextField5");
		jTextField5.setBounds(510, 310, 67, 23);
		jLayeredPane1.add(jTextField5, javax.swing.JLayeredPane.DEFAULT_LAYER);

		jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(
				new String[] { "影厅名称" }));
		jComboBox3.addItemListener(new java.awt.event.ItemListener() {
			public void itemStateChanged(java.awt.event.ItemEvent evt) {
				jComboBox3ItemStateChanged(evt);
			}
		});
		jComboBox3.setBounds(330, 40, 100, 23);
		jLayeredPane1.add(jComboBox3, javax.swing.JLayeredPane.DEFAULT_LAYER);

		jButton5.setText("\u91cd\u7f6e");
		jButton5.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton5ActionPerformed(evt);
			}
		});
		jButton5.setBounds(200, 380, 60, 25);
		jLayeredPane1.add(jButton5, javax.swing.JLayeredPane.DEFAULT_LAYER);

		jButton6.setText("\u4fee\u6539");
		jButton6.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton6ActionPerformed(evt);
			}
		});
		jButton6.setBounds(420, 380, 60, 25);
		jLayeredPane1.add(jButton6, javax.swing.JLayeredPane.DEFAULT_LAYER);

		jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(
				new String[] { "影片名称" }));
		jComboBox1.setBounds(120, 340, 90, 23);
		jLayeredPane1.add(jComboBox1, javax.swing.JLayeredPane.DEFAULT_LAYER);

		jButton8.setText("\u6dfb\u52a0");
		jButton8.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton8ActionPerformed(evt);
			}
		});
		jButton8.setBounds(350, 380, 60, 25);
		jLayeredPane1.add(jButton8, javax.swing.JLayeredPane.DEFAULT_LAYER);

		jTextField2.setText("jTextField1");
		jTextField2.setBounds(120, 290, 90, 23);
		jLayeredPane1.add(jTextField2, javax.swing.JLayeredPane.DEFAULT_LAYER);

		jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(
				new String[] { "影厅名称" }));
		jComboBox2.setBounds(340, 290, 100, 23);
		jLayeredPane1.add(jComboBox2, javax.swing.JLayeredPane.DEFAULT_LAYER);

		jTextField4.setText("jTextField3");
		jTextField4.setBounds(360, 340, 100, 23);
		jLayeredPane1.add(jTextField4, javax.swing.JLayeredPane.DEFAULT_LAYER);
		jLabel5.setBounds(30, 280, 560, 150);
		jLayeredPane1.add(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 685,
				Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 522,
				Short.MAX_VALUE));
	}// </editor-fold>
	//GEN-END:initComponents

	private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		String pal_id = jTextField2.getText();
		String hal_id = "";
		String mov_id = "";
		if(this.jComboBox2.getSelectedIndex()>0){
			hal_id = halls.get(this.jComboBox2.getSelectedIndex() - 1).getHal_id();
		}
		String mov_name = this.jComboBox1.getSelectedItem().toString();
		if(this.jComboBox1.getSelectedIndex()>0){
			mov_id = movies.get(this.jComboBox1.getSelectedIndex() - 1).getId();
		}
		String pla_Starttime = this.jTextField4.getText();
		String tic_price = this.jTextField5.getText();
		if (Bool.isEmpty(pal_id)) {
			JOptionPane.showMessageDialog(null, "场次编号不能为空！");
			return;
		}
		if (Bool.isEmpty(hal_id)) {
			JOptionPane.showMessageDialog(null, "影厅名称不能为空！");
			return;
		}
		if (Bool.isEmpty(mov_id)) {
			JOptionPane.showMessageDialog(null, "影片名称不能为空！");
			return;
		}
		if (Bool.isEmpty(this.jTextField4.getText())) {
			JOptionPane.showMessageDialog(null, "影片起始放映时间不能为空！");
			return;
		}
		if (Bool.isEmpty(this.jTextField5.getText())) {
			JOptionPane.showMessageDialog(null, "影片票价不能为空！");
			return;
		}

		Play play = new Play(pal_id, hal_id, mov_id, pla_Starttime, tic_price);
		int modifyNum = playDao.add(play);
		if (modifyNum == 1) {
			JOptionPane.showMessageDialog(null, "添加成功！");
			resetValue();
			this.fillTable(new Play());
		} else if (modifyNum == -2) {
			JOptionPane.showMessageDialog(null, "添加失败！该场次编号已存在！");
		}else {
			JOptionPane.showMessageDialog(null, "添加失败！");
		}
	}

	private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		int row = jTable1.getSelectedRow();//取得表格选中行
		if(row>-1){
			

		String pal_id = jTable1.getValueAt(row, 0).toString();
		String hal_name = this.jComboBox2.getSelectedItem().toString();
		String hal_id = "";
		String mov_id = "";
		if(this.jComboBox2.getSelectedIndex()>0){
			hal_id = halls.get(this.jComboBox2.getSelectedIndex() - 1).getHal_id();
		}
		String mov_name = this.jComboBox1.getSelectedItem().toString();
		if(this.jComboBox1.getSelectedIndex()>0){
			mov_id = movies.get(this.jComboBox1.getSelectedIndex() - 1).getId();
		}
		

		String pla_Starttime = this.jTextField4.getText();
		String tic_price = this.jTextField5.getText();

		if (Bool.isEmpty(jTable1.getValueAt(row, 0).toString())) {
			JOptionPane.showMessageDialog(null, "请选择你要修改的记录！");
			return;
		}
		if (Bool.isEmpty(hal_id)) {
			JOptionPane.showMessageDialog(null, "影厅名称不能为空！");
			return;
		}
		if (Bool.isEmpty(mov_id)) {
			JOptionPane.showMessageDialog(null, "影片名称不能为空！");
			return;
		}
		if (Bool.isEmpty(this.jTextField4.getText())) {
			JOptionPane.showMessageDialog(null, "影片起始放映时间不能为空！");
			return;
		}
		if (Bool.isEmpty(this.jTextField5.getText())) {
			JOptionPane.showMessageDialog(null, "影片票价不能为空！");
			return;
		}

		Play play = new Play(pal_id, hal_id, mov_id, pla_Starttime, tic_price);
		int modifyNum = playDao.update(play);
		if (modifyNum == 1) {
			JOptionPane.showMessageDialog(null, "修改成功！");
			resetValue();
			this.fillTable(new Play());
		} else {
			JOptionPane.showMessageDialog(null, "修改失败！");
		}		
		}else{
			JOptionPane.showMessageDialog(null, "请选择要修改数据！");
		}
	}

	private void jComboBox3ItemStateChanged(java.awt.event.ItemEvent evt) {
		// TODO add your handling code here:
		Play play = new Play();
		String hallnameselect = this.jComboBox3.getSelectedItem().toString();
		if (hallnameselect == "影厅名称") {
			hallnameselect = "";
		}
		play.setHal_name(hallnameselect);
		fillTable(play);
	}

	private void jScrollPane1MousePressed(java.awt.event.MouseEvent evt) {
		// TODO add your handling code here:
	}

	private void jTable1MousePressed(java.awt.event.MouseEvent evt) {
		// TODO add your handling code here:
		// TODO add your handling code here:
		int row = this.jTable1.getSelectedRow();
		this.jTextField2.setText(this.jTable1.getValueAt(row, 0).toString());
		this.jComboBox1.setSelectedItem(this.jTable1.getValueAt(row, 3)
				.toString());
		this.jTextField4.setText(this.jTable1.getValueAt(row, 4).toString());
		this.jTextField5.setText(this.jTable1.getValueAt(row, 6).toString());
		this.jComboBox2.setSelectedItem(this.jTable1.getValueAt(row, 1)
				.toString());
	}

	private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		resetValue();
	}

	private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		// TODO add your handling code here:
		int row = jTable1.getSelectedRow();//取得表格选中行
		if(row>-1){
		String pla_id = jTable1.getValueAt(row, 0).toString();
		int n = JOptionPane.showConfirmDialog(null, "确定要删除这条记录吗？");
		if (n == 0) {
			Play play = new Play(pla_id);
			int delecteNum = playDao.delete(play);
			if (delecteNum == 1) {
				JOptionPane.showMessageDialog(null, "删除成功！");
				resetValue();
				this.fillTable(new Play());
			} else {
				JOptionPane.showMessageDialog(null, "删除失败！");
			}
		}}else{
			JOptionPane.showMessageDialog(null, "请选择你要删除的记录！");
			return;
		}
	}

	private void resetValue() {
		// TODO Auto-generated method stub
		this.jTextField2.setText("");
		this.jComboBox1.setSelectedItem("影片名称");
		this.jTextField4.setText("");
		this.jTextField5.setText("");
		this.jComboBox2.setSelectedItem("影厅名称");

	}

	private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		Play play = new Play();
		play.setMov_name(jTextField1.getText());
		fillTable(play);
	}

	private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {
		// TODO add your handling code here:
		Play play = new Play();
		play.setMov_name(jTextField1.getText());
		fillTable(play);
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton3;
	private javax.swing.JButton jButton4;
	private javax.swing.JButton jButton5;
	private javax.swing.JButton jButton6;
	private javax.swing.JButton jButton8;
	private javax.swing.JComboBox jComboBox1;
	private javax.swing.JComboBox jComboBox2;
	private javax.swing.JComboBox jComboBox3;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLayeredPane jLayeredPane1;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTable jTable1;
	private javax.swing.JTextField jTextField1;
	private javax.swing.JTextField jTextField2;
	private javax.swing.JTextField jTextField4;
	private javax.swing.JTextField jTextField5;
	// End of variables declaration//GEN-END:variables

}