/*
 * SaleMain.java
 *
 * Created on __DATE__, __TIME__
 */

package Sale;

import java.util.ArrayList;
import java.util.List;
import java.util.Vector;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import User.Hall;
import User.Play;
import User.Ticket;
import UserDao.HallDao;
import UserDao.PlayDao;
import UserDao.TicketDao;

/**
 *
 * @author  __USER__
 */
public class SaleMain extends javax.swing.JPanel {
	PlayDao pdao = new PlayDao();
	TicketDao tdao = new TicketDao();
	List<Play> listPlays = null;
	/** Creates new form SaleMain */
	public SaleMain() {
		initComponents();
		fillTable(new Play());
	}

	private void fillTable(Play play) {
		// TODO Auto-generated method stub
		DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
		dtm.setRowCount(0);
		listPlays = pdao.list(play.getMov_name());
		if (listPlays.size() != 0) {
			for (int i = 0; i < listPlays.size(); i++) {
				play = listPlays.get(i);
				Vector v = new Vector();
				v.add(play.getMov_name());
				v.add(play.getHal_name());
				v.add(play.getPla_starttime());
				v.add(play.getMov_time());
				List<Ticket> lisTickets = tdao.list(play.getPla_id());
				v.add(play.getHal_count() - lisTickets.size());

				v.add(play.getTic_price());
				dtm.addRow(v);
			}
		}
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLayeredPane1 = new javax.swing.JLayeredPane();
		jScrollPane1 = new javax.swing.JScrollPane();
		jTable1 = new javax.swing.JTable();
		jTextField1 = new javax.swing.JTextField();
		jButton2 = new javax.swing.JButton();
		jLabel2 = new javax.swing.JLabel();
		jLabel1 = new javax.swing.JLabel();

		jTable1.setModel(new javax.swing.table.DefaultTableModel(
				new Object[][] { { null, null, null, null, null, null },
						{ null, null, null, null, null, null },
						{ null, null, null, null, null, null },
						{ null, null, null, null, null, null },
						{ null, null, null, null, null, null } }, new String[] {
						"电影名称", "影厅名称", "放映时间", "放映时长", "剩余座位", "电影票价" }) {
			boolean[] canEdit = new boolean[] { false, false, false, false,
					true, true };

			public boolean isCellEditable(int rowIndex, int columnIndex) {
				return canEdit[columnIndex];
			}
		});
		jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mousePressed(java.awt.event.MouseEvent evt) {
				jTable1MousePressed(evt);
			}
		});
		jScrollPane1.setViewportView(jTable1);

		jScrollPane1.setBounds(40, 70, 510, 330);
		jLayeredPane1.add(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

		jTextField1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextField1ActionPerformed(evt);
			}
		});
		jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
			public void keyPressed(java.awt.event.KeyEvent evt) {

			}

			public void keyTyped(java.awt.event.KeyEvent evt) {
				jTextField1KeyTyped(evt);
			}
		});
		jTextField1.setBounds(180, 20, 130, 23);
		jLayeredPane1.add(jTextField1, javax.swing.JLayeredPane.DEFAULT_LAYER);

		jButton2.setText("\u9009\u5ea7");
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});
		jButton2.setBounds(440, 20, 60, 25);
		jLayeredPane1.add(jButton2, javax.swing.JLayeredPane.DEFAULT_LAYER);

		jLabel2
				.setText("\u8f93\u5165\u7535\u5f71\u540d\u79f0\u67e5\u8be2\uff1a");
		jLabel2.setBounds(40, 20, 130, 17);
		jLayeredPane1.add(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
		jLabel1.setBounds(0, 0, 600, 430);
		jLayeredPane1.add(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 600,
				Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 430,
				Short.MAX_VALUE));
	}// </editor-fold>
	//GEN-END:initComponents

	private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {
		// TODO add your handling code here:
		Play play = new Play();
		play.setMov_name(jTextField1.getText());
		fillTable(play);
	}

	private void jTable1MousePressed(java.awt.event.MouseEvent evt) {
		// TODO add your handling code here:

	}

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		int row = jTable1.getSelectedRow();//取得表格选中行
		if (row > -1) {
			HallDao dao = new HallDao();
			List<Ticket> lisTickets = tdao.list(listPlays.get(row).getPla_id());
			List<Hall> list = dao.list(jTable1.getValueAt(row, 1).toString());
			Hall hall = list.get(0);
			this.removeAll();
			SeatHall seatHall = new SeatHall(hall, lisTickets, listPlays.get(row).getPla_id());
			this.setSize(600, 400);
			seatHall.setSize(600, 400);
			seatHall.setVisible(true);
			this.add(seatHall);
			this.validate();
			this.repaint();
		} else {
			JOptionPane.showMessageDialog(null, "请选择要购买的场次！");
		}

		//String hal_id = hall.getHal_id();

	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton2;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLayeredPane jLayeredPane1;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTable jTable1;
	private javax.swing.JTextField jTextField1;
	// End of variables declaration//GEN-END:variables

}