/*
 * SeatHall.java
 *
 * Created on __DATE__, __TIME__
 */

package Sale;

import java.util.ArrayList;
import java.util.List;

import javax.swing.JOptionPane;
import javax.swing.JPanel;

import Factory.JPanelFactory;
import User.Hall;
import User.LoginID;
import User.Ticket;
import UserDao.TicketDao;

/**
 *
 * @author  __USER__
 */
public class SeatHall extends javax.swing.JPanel {

	List<Seat> list = new ArrayList<Seat>();
	List<Ticket> listTi = null;
	Hall hall = null;
	String pla_id = "";

	/** Creates new form SeatHall */
	public SeatHall(Hall hal, List<Ticket> listT, String pla_id) {
		initComponents();
		this.pla_id = pla_id;
		listTi = listT;
		hall = hal;
		int sum = 1;
		for (int i = 0; i < hall.getHal_rows(); i++) {
			for (int j = 0; j < hall.getHal_seats(); j++) {
				Seat se = null;
				for (int j2 = 0; j2 < listTi.size(); j2++) {
					if (listTi.get(j2).getHal_number() == sum) {
						se = new Seat(-1);
						break;
					} else {
						se = new Seat(0);
					}
				}
				se.setBounds(50 + 25 * j, 50 + 25 * i, 20, 20);
				se.adaptive();
				this.add(se);
				list.add(se);
				sum++;
			}
		}
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jButton1 = new javax.swing.JButton();
		jLabel1 = new javax.swing.JLabel();

		jButton1.setText("\u8d2d\u4e70");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jLabel1.setBackground(new java.awt.Color(0, 0, 0));
		jLabel1.setText("\u5c4f\u5e55");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				javax.swing.GroupLayout.Alignment.TRAILING,
				layout.createSequentialGroup().addContainerGap(399,
						Short.MAX_VALUE).addComponent(jButton1,
						javax.swing.GroupLayout.PREFERRED_SIZE, 93,
						javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap()).addGroup(
				layout.createSequentialGroup().addGap(223, 223, 223)
						.addComponent(jLabel1).addContainerGap(257,
								Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				javax.swing.GroupLayout.Alignment.TRAILING,
				layout.createSequentialGroup().addContainerGap().addComponent(
						jLabel1).addPreferredGap(
						javax.swing.LayoutStyle.ComponentPlacement.RELATED,
						279, Short.MAX_VALUE).addComponent(jButton1)
						.addContainerGap()));
	}// </editor-fold>
	//GEN-END:initComponents

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		List<String> zuowei = new ArrayList<String>();
		List<String> sum = new ArrayList<String>();
		for (int i = 0; i < list.size(); i++) {
			if (list.get(i).getisPitchOn() == 1) {
				int zuo = i % hall.getHal_seats() + 1;
				int pai = i / hall.getHal_seats() + 1;
				sum.add(Integer.toString(i + 1));
				String zw = pai + "排" + zuo + "坐";
				zuowei.add(zw);
			}
		}
		if (zuowei.size() > 5) {
			JOptionPane.showMessageDialog(null, "每人限购5张", "超出购买数量",
					JOptionPane.ERROR_MESSAGE);
		} else if (zuowei.size() == 0) {
			JOptionPane.showMessageDialog(null, "请选择要购买的座位", "购买数不能为0",
					JOptionPane.ERROR_MESSAGE);
		} else {
			int isDelete = JOptionPane.showConfirmDialog(null, zuowei, "是否购买",
					JOptionPane.YES_NO_OPTION);
			if (isDelete == JOptionPane.YES_OPTION) {
				Ticket ticket = null;
				TicketDao ticketDao = new TicketDao();
				int f = -1;
				for (int i = 0; i < zuowei.size(); i++) {
					ticket = new Ticket();
					ticket.setTic_id(Tic_Random.getRandomString(8));
					ticket.setHal_number(Integer.parseInt(sum.get(i)));
					ticket.setPla_id(pla_id);
					ticket.setTic_code(Tic_Random.getRandomString(9));
					ticket.setCus_id(LoginID.getInstance().CusId);
					f = ticketDao.add(ticket);
					list.get(Integer.parseInt(sum.get(i)) - 1).setisPitchOn(-1);
				}

				if (f > 0) {
					JOptionPane.showMessageDialog(null, "购买成功");
					this.removeAll();
					JPanel saleMain = JPanelFactory.GetJPanel("SaleMain");
					this.setSize(600, 400);
					saleMain.setSize(600, 400);
					saleMain.setVisible(true);
					this.add(saleMain);
					this.validate();
					this.repaint();
				} else {
					JOptionPane.showMessageDialog(null, "购买失败");
				}
			}
		}
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JLabel jLabel1;
	// End of variables declaration//GEN-END:variables

}