/*
 * MovieMain.java
 *
 * Created on __DATE__, __TIME__
 */

package Movie;

import java.util.List;
import java.util.Vector;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import User.Movie;
import User.Play;
import UserDao.MovieDao;

/**
 *
 * @author  __USER__
 */
public class MovieMain extends javax.swing.JPanel {
	MovieDao movieDao = new MovieDao();
	List<Movie> listMovies = null;

	/** Creates new form MovieMain */
	public MovieMain() {
		initComponents();
		fillTable(new Movie());
	}

	private void fillTable(Movie movie) {
		// TODO Auto-generated method stub
		DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
		dtm.setRowCount(0);
		listMovies = movieDao.list(movie.getName());
		if (listMovies.size() != 0) {
			for (int i = 0; i < listMovies.size(); i++) {
				movie = listMovies.get(i);
				Vector v = new Vector();
				v.add(movie.getId());
				v.add(movie.getName());
				//v.add(movie.getIntroduce());
				v.add(movie.getIndate());
				//v.add(movie.getOutdate());
				v.add(movie.getTime());
				//v.add(movie.getDirector());
				//v.add(movie.getStar());
				v.add(movie.getStyle());
				v.add(movie.getKind());
				dtm.addRow(v);
			}
		}

	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLayeredPane1 = new javax.swing.JLayeredPane();
		jPanel1 = new javax.swing.JPanel();
		jTextField1 = new javax.swing.JTextField();
		jButton1 = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();
		jButton3 = new javax.swing.JButton();
		jButton4 = new javax.swing.JButton();
		jScrollPane1 = new javax.swing.JScrollPane();
		jTable1 = new javax.swing.JTable();
		jLabel1 = new javax.swing.JLabel();

		jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

		jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
			public void keyPressed(java.awt.event.KeyEvent evt) {
				jTextField1KeyPressed(evt);
			}
		});

		jButton1.setText("\u67e5\u8be2");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jButton2.setText("\u6dfb\u52a0");
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});

		jButton3.setText("\u4fee\u6539");
		jButton3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton3ActionPerformed(evt);
			}
		});

		jButton4.setText("\u5220\u9664");
		jButton4.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton4ActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
				jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout
				.setHorizontalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addGap(26, 26, 26)
										.addComponent(
												jTextField1,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												122,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jButton1)
										.addGap(93, 93, 93)
										.addComponent(jButton2)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(jButton3)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(jButton4)
										.addContainerGap(28, Short.MAX_VALUE)));
		jPanel1Layout
				.setVerticalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																jTextField1,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jButton1)
														.addComponent(jButton2)
														.addComponent(jButton3)
														.addComponent(jButton4))
										.addContainerGap(18, Short.MAX_VALUE)));

		jPanel1.setBounds(30, 20, 540, 70);
		jLayeredPane1.add(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

		jTable1.setModel(new javax.swing.table.DefaultTableModel(
				new Object[][] { { null, null, null, null, null, null },
						{ null, null, null, null, null, null },
						{ null, null, null, null, null, null },
						{ null, null, null, null, null, null } }, new String[] {
						"电影编号", "电影名称", "上映时间", "电影时长", "电影规格", "电影分类" }));
		jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mousePressed(java.awt.event.MouseEvent evt) {
				jTable1MousePressed(evt);
			}
		});
		jScrollPane1.setViewportView(jTable1);

		jScrollPane1.setBounds(30, 100, 540, 170);
		jLayeredPane1.add(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
		jLabel1.setBounds(0, 0, 620, 430);
		jLayeredPane1.add(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				layout.createSequentialGroup().addComponent(jLayeredPane1,
						javax.swing.GroupLayout.PREFERRED_SIZE, 623,
						javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
								Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 430,
				Short.MAX_VALUE));
	}// </editor-fold>
	//GEN-END:initComponents

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		Movie movie = new Movie();
		movie.setName(jTextField1.getText());
		fillTable(movie);
	}

	private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {
		// TODO add your handling code here:
		Movie movie = new Movie();
		movie.setName(jTextField1.getText());
		fillTable(movie);
	}

	private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		// TODO add your handling code here:
		// TODO add your handling code here:
		int row = jTable1.getSelectedRow();//取得表格选中行
		if(row>-1){
			String movie_id = jTable1.getValueAt(row, 0).toString();
			int n = JOptionPane.showConfirmDialog(null, "确定要删除这条记录吗？");
			if (n == 0) {
				Movie movie = new Movie();
				movie.setId(movie_id);
				int delecteNum = movieDao.delete(movie);
				if (delecteNum == 1) {
					JOptionPane.showMessageDialog(null, "删除成功！");
					this.fillTable(new Movie());
				} else {
					JOptionPane.showMessageDialog(null, "删除失败！");
				}
			}
		}else{
			JOptionPane.showMessageDialog(null, "请选择你要删除的记录！");
			return;
		}
	}

	private void resetValue() {
		// TODO Auto-generated method stub
		
	}

	private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		int row = jTable1.getSelectedRow();
		if(row>-1){
			this.removeAll();
			MovieModify movieModify = new MovieModify(listMovies.get(row));
			movieModify.setSize(600, 700);
			this.setSize(600, 700);
			this.add(movieModify);
			this.setVisible(true);
			this.validate();
			this.repaint();
		}else{
			JOptionPane.showMessageDialog(null, "请选择要修改的数据！");
		}
	}

	private void jTable1MousePressed(java.awt.event.MouseEvent evt) {
		// TODO add your handling code here:
	}

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
		this.removeAll();
		MovieAdd movieAdd = new MovieAdd();
		movieAdd.setSize(600, 700);
		this.setSize(600, 700);
		this.add(movieAdd);
		this.setVisible(true);
		this.validate();
		this.repaint();

	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JButton jButton3;
	private javax.swing.JButton jButton4;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLayeredPane jLayeredPane1;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTable jTable1;
	private javax.swing.JTextField jTextField1;
	// End of variables declaration//GEN-END:variables

}