/*
 * MovieAdd.java
 *
 * Created on __DATE__, __TIME__
 */

package Movie;

import java.awt.Image;
import java.util.Date;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

import Bool.Bool;
import User.Movie;
import User.Play;
import UserDao.MovieDao;

/**
 *
 * @author  __USER__
 */
public class MovieAdd extends javax.swing.JPanel {
	MovieDao movieDao = new MovieDao();

	/** Creates new form MovieAdd */
	public MovieAdd() {
		initComponents();
		ImageIcon image = (ImageIcon) jLabel1.getIcon();
		image.setImage(image.getImage().getScaledInstance(jLabel1.getWidth(),
				jLabel1.getHeight(), Image.SCALE_DEFAULT));
		jLabel1.setIcon(image);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLayeredPane1 = new javax.swing.JLayeredPane();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel11 = new javax.swing.JLabel();
		jScrollPane1 = new javax.swing.JScrollPane();
		jTextArea1 = new javax.swing.JTextArea();
		jButton1 = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();
		jLabel6 = new javax.swing.JLabel();
		jLabel7 = new javax.swing.JLabel();
		jLabel8 = new javax.swing.JLabel();
		jLabel9 = new javax.swing.JLabel();
		jLabel10 = new javax.swing.JLabel();
		jTextField1 = new javax.swing.JTextField();
		jTextField2 = new javax.swing.JTextField();
		jTextField3 = new javax.swing.JTextField();
		jTextField4 = new javax.swing.JTextField();
		jTextField5 = new javax.swing.JTextField();
		jTextField6 = new javax.swing.JTextField();
		jTextField7 = new javax.swing.JTextField();
		jTextField8 = new javax.swing.JTextField();
		jTextField9 = new javax.swing.JTextField();
		jLabel13 = new javax.swing.JLabel();
		jLabel12 = new javax.swing.JLabel();

		jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/img/chaoren.jpg"))); // NOI18N
		jLabel1.setBounds(30, 50, 150, 170);
		jLayeredPane1.add(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

		jLabel2.setText("\u7535\u5f71\u6d77\u62a5\uff1a");
		jLabel2.setBounds(20, 20, 60, 17);
		jLayeredPane1.add(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

		jLabel11.setText("\u5f71\u7247\u7b80\u4ecb\uff1a");
		jLabel11.setBounds(20, 240, 60, 17);
		jLayeredPane1.add(jLabel11, javax.swing.JLayeredPane.DEFAULT_LAYER);

		jTextArea1.setColumns(20);
		jTextArea1.setRows(5);
		jScrollPane1.setViewportView(jTextArea1);

		jScrollPane1.setBounds(90, 246, 470, 130);
		jLayeredPane1.add(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

		jButton1.setText("\u91cd\u7f6e");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});
		jButton1.setBounds(120, 390, 57, 25);
		jLayeredPane1.add(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);

		jButton2.setText("\u6dfb\u52a0");
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});
		jButton2.setBounds(460, 390, 57, 25);
		jLayeredPane1.add(jButton2, javax.swing.JLayeredPane.DEFAULT_LAYER);

		jLabel3.setText("\u7535\u5f71\u7f16\u53f7\uff1a");
		jLabel3.setBounds(200, 40, 60, 17);
		jLayeredPane1.add(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

		jLabel4.setText("\u7535\u5f71\u540d\u79f0\uff1a");
		jLabel4.setBounds(400, 40, 60, 17);
		jLayeredPane1.add(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);

		jLabel5.setText("\u4e0a\u6620\u65f6\u95f4\uff1a");
		jLabel5.setBounds(200, 90, 60, 17);
		jLayeredPane1.add(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);

		jLabel6.setText("\u4e0b\u6620\u65f6\u95f4\uff1a");
		jLabel6.setBounds(400, 90, 60, 17);
		jLayeredPane1.add(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);

		jLabel7.setText("\u5bfc\u6f14\uff1a");
		jLabel7.setBounds(225, 140, 36, 17);
		jLayeredPane1.add(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);

		jLabel8.setText("\u4e3b\u6f14\uff1a");
		jLabel8.setBounds(425, 140, 36, 17);
		jLayeredPane1.add(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);

		jLabel9.setText("\u5f71\u7247\u7c7b\u578b\uff1a");
		jLabel9.setBounds(400, 190, 60, 17);
		jLayeredPane1.add(jLabel9, javax.swing.JLayeredPane.DEFAULT_LAYER);

		jLabel10.setText("\u5f71\u7247\u683c\u5f0f\uff1a");
		jLabel10.setBounds(200, 190, 60, 17);
		jLayeredPane1.add(jLabel10, javax.swing.JLayeredPane.DEFAULT_LAYER);
		jTextField1.setBounds(270, 35, 90, 23);
		jLayeredPane1.add(jTextField1, javax.swing.JLayeredPane.DEFAULT_LAYER);
		jTextField2.setBounds(470, 40, 90, 23);
		jLayeredPane1.add(jTextField2, javax.swing.JLayeredPane.DEFAULT_LAYER);
		jTextField3.setBounds(270, 85, 90, 23);
		jLayeredPane1.add(jTextField3, javax.swing.JLayeredPane.DEFAULT_LAYER);
		jTextField4.setBounds(470, 85, 90, 23);
		jLayeredPane1.add(jTextField4, javax.swing.JLayeredPane.DEFAULT_LAYER);
		jTextField5.setBounds(270, 135, 90, 23);
		jLayeredPane1.add(jTextField5, javax.swing.JLayeredPane.DEFAULT_LAYER);
		jTextField6.setBounds(470, 135, 90, 23);
		jLayeredPane1.add(jTextField6, javax.swing.JLayeredPane.DEFAULT_LAYER);
		jTextField7.setBounds(270, 185, 90, 23);
		jLayeredPane1.add(jTextField7, javax.swing.JLayeredPane.DEFAULT_LAYER);
		jTextField8.setBounds(470, 185, 90, 23);
		jLayeredPane1.add(jTextField8, javax.swing.JLayeredPane.DEFAULT_LAYER);
		jTextField9.setBounds(270, 220, 90, 23);
		jLayeredPane1.add(jTextField9, javax.swing.JLayeredPane.DEFAULT_LAYER);

		jLabel13.setText("\u65f6\u957f\uff1a");
		jLabel13.setBounds(210, 220, 36, 17);
		jLayeredPane1.add(jLabel13, javax.swing.JLayeredPane.DEFAULT_LAYER);
		jLabel12.setBounds(0, 0, 600, 430);
		jLayeredPane1.add(jLabel12, javax.swing.JLayeredPane.DEFAULT_LAYER);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 600,
				Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 430,
				Short.MAX_VALUE));
	}// </editor-fold>
	//GEN-END:initComponents

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		String id = jTextField1.getText();
		String name = jTextField2.getText();
		String indate = jTextField3.getText();
		String outdate = jTextField4.getText();
		String time = jTextField9.getText();
		String director = jTextField5.getText();
		String star = jTextField6.getText();
		String style = jTextField7.getText();
		String kind = jTextField8.getText();
		String introduce = jTextArea1.getText();
		if (Bool.isEmpty(id) || Bool.isEmpty(name)
				|| Bool.isEmpty(indate.toString())
				|| Bool.isEmpty(outdate.toString()) || Bool.isEmpty(time)
				|| Bool.isEmpty(director) || Bool.isEmpty(star)
				|| Bool.isEmpty(style) || Bool.isEmpty(kind)
				|| Bool.isEmpty(introduce)) {
			JOptionPane.showMessageDialog(null, "请输入完整信息！");
			return;
		}

		Movie movie = new Movie(id, name, introduce, indate, outdate, time,
				director, star, style, kind);
		int modifyNum = movieDao.add(movie);
		if (modifyNum == 1) {
			JOptionPane.showMessageDialog(null, "添加成功！");
			resetValue();
		} else if (modifyNum == -2) {
			JOptionPane.showMessageDialog(null, "添加失败！该电影编号已存在！");
		} else {
			JOptionPane.showMessageDialog(null, "添加失败！");
		}
	}

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		resetValue();

	}

	private void resetValue() {
		// TODO Auto-generated method stub
		this.jTextField1.setText("");
		this.jTextField2.setText("");
		this.jTextField3.setText("");
		this.jTextField4.setText("");
		this.jTextField5.setText("");
		this.jTextField6.setText("");
		this.jTextField7.setText("");
		this.jTextField8.setText("");
		this.jTextArea1.setText("");

	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel10;
	private javax.swing.JLabel jLabel11;
	private javax.swing.JLabel jLabel12;
	private javax.swing.JLabel jLabel13;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JLayeredPane jLayeredPane1;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTextArea jTextArea1;
	private javax.swing.JTextField jTextField1;
	private javax.swing.JTextField jTextField2;
	private javax.swing.JTextField jTextField3;
	private javax.swing.JTextField jTextField4;
	private javax.swing.JTextField jTextField5;
	private javax.swing.JTextField jTextField6;
	private javax.swing.JTextField jTextField7;
	private javax.swing.JTextField jTextField8;
	private javax.swing.JTextField jTextField9;
	// End of variables declaration//GEN-END:variables

}